In [3]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [4]:
x = np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [5]:
y = np.zeros((3, 3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [6]:
all = x + y
all

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [7]:
print(x.ndim, x.shape, x.size, x.dtype)

2 (3, 3) 9 float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [8]:
w = np.arange(11, 17)
w = w.reshape(3,2)
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [9]:
z = np.arange(1,4)
z


array([1, 2, 3])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [10]:
z = z.reshape(3,1)
new_array = np.hstack((z, w))
new_array

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [26]:
for row in new_array :
    for i in row : 
        print(i)



1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [39]:
rev = np.transpose(new_array)
rev


array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [31]:
new_array - 1

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [14]:
max_value = np.max(new_array)
min_value = np.min(new_array)
max_value , min_value

(16, 1)

## Q#12: Print the first row of "newArray" using indexing.

In [34]:
new_array[0]

array([ 1, 11, 12])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [37]:
new_array [0,2]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [18]:
sub_arr = new_array[0:-13]


## Q#15: Change the shape of "newArray" to (9,1).

In [38]:
new_array.reshape(9,1)

array([[ 1],
       [11],
       [12],
       [ 2],
       [13],
       [14],
       [ 3],
       [15],
       [16]])

## Q#16: Change the shape of "newArray" to (3,2).

In [ ]:
none

# Well Done 🎉